### PR TITLE
LPS-105151 Fix invocations adding the filter by company

### PR DESCRIPTION
**Pull request by martamedio**

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@martamedio Overall approach looks good I think. I like the system level factory instances being included, though I am wondering how we can communicate this to the instance level admins.
I think it is impossible to not allow system level factory instances to be created right now, so maybe this was a situation we were forced into?

Please see martamedio/liferay-portal/pull/140
The main issues I fixed was 
* remove use of ThreadLocal (ManagedServiceFactory is invoked asynchronously)
* the refactor (last commit) was to avoid GC with strings for from the getOpenIdConnectProviderNames() method. Its called whenever the login portlet is rendered, sometimes twice. The refactor is mostly for discussion. Maybe the original approach is ok.

**Pull request closed without merging**
