### PR TITLE
LPS-67115

### PR DESCRIPTION
**Pull request by topolik**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
These changes make sense to me. I have verified that when used in an upgrade the result is as expected: GROUP_SCOPE records for all sites for all relevant roles. Also I have verified that after starting portal, the root model resource permission record is there as well. As a consequence of the deployment process calling PortletLocalServiceImpl#checkPortlet(...) .

So once we have resolved the conversations on the previous pull topolik/liferay-portal/pull/368 I think we're good.

**Comment by topolik** [comment]
Thanks Stian for the checks!

Then, once you finish the commits merging, can you please forward it to Sergio and points to those comments?

Thank you.

**Comment by stian-sigvartsen** [comment]
Will do :)

**Comment by stian-sigvartsen** [comment]
See liferay-portal/pull/477

**Pull request closed without merging**
