### PR TITLE
[TS] LPS-115559 Add SAML binding context to the outbound message context

### PR DESCRIPTION
**Pull request by hudakl**
Hi Stian,

Could you please review this fix for LPS-115559?

Thank you,
Laci

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:saml

**Comment by lipusz** [comment]
Hello Laci, @hudakl 

Can you please look into the failure in     `LocalFile.SAML#ViewSPInitiatedSSOWithMultipleIdPsAndAssertRenderLoginPortletWithoutIdpsMatched`?

If you are not sure if it's related to your changes, you can reach out to @gaborlovasdotcom for help.

Thanks!

**Comment by stian-sigvartsen** [comment]
@lipusz I have manually tested the showing of the login portlet when no IdP connections are matched. The failure is likely caused by something else. I've sent myself the commit and triggered another CI test. Please see stian-sigvartsen/liferay-portal/pull/258

**Comment by stian-sigvartsen** [comment]
@hudakl . All tests passed this time and I have forwarded to Brian. Thanks for fixing the bug!

**Pull request closed without merging**
