### PR TITLE
LPS-108070 New module for SameSite Cookies support

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by stian-sigvartsen** [comment]
ci:test:clustering

**Comment by xbrianlee** [comment]
ci:test:security:norebase

**Comment by xbrianlee** [comment]
ci:test:bundle:norebase

**Comment by xbrianlee** [comment]
ci:test:security:norebase

**Comment by xbrianlee** [comment]
ci:test:bundle:norebase

**Comment by xbrianlee** [comment]
ci:test:security:norebase

**Comment by xbrianlee** [comment]
ci:test:bundle:norebase

**Comment by stian-sigvartsen** [comment]
Relevant CI failure in clustering

**Pull request closed without merging**
