### PR TITLE
[TS] LPS-102763 LDAP password gets overridden if the login fails for the first time

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-102763

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
Ci tests ran on https://github.com/NorbertKocsis/liferay-portal/pull/65

**Comment by stian-sigvartsen** [comment]
Just started reviewing...

**Comment by stian-sigvartsen** [comment]
Hi @NorbertKocsis. Did you explore alternate approaches which doesn't include setting a ThreadLocal?

**Comment by stian-sigvartsen** [comment]
The main cause of this issue is that the initial user import sets the PasswordModifiecationThreadLocal to true unnecessarily (I think). I've sent a simple prospective solution to @topolik for validation.

Please see topolik/liferay-portal/pull/821

**Pull request closed without merging**
