### PR TITLE
OAUTH2-157 Fix tests in master 2

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@stian-sigvartsen failure in `JsonWebServiceTest.test`, looks like the same exception
```[OAuth2JSONWSSAPEntryActivator:137] Unable to add service access policy entry for company 20100
com.liferay.portal.security.service.access.policy.exception.SAPEntryTitleException
	at com.liferay.portal.security.service.access.policy.service.impl.SAPEntryLocalServiceImpl.validate(SAPEntryLocalServiceImpl.java:345)
	at com.liferay.portal.security.service.access.policy.service.impl.SAPEntryLocalServiceImpl.addSAPEntry(SAPEntryLocalServiceImpl.java:70)```
https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/91326/AXIS_VARIABLE=0,label_exp=!master/consoleFull
same error in portal smoke https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/230284/AXIS_VARIABLE=0,label_exp=!master/console

**Comment by stian-sigvartsen** [comment]
@jpince hmm it passed on localhost. I'm going to have to look into it further in the morning

**Comment by jpince** [comment]
@stian-sigvartsen I understand. I'm testing a revert so CI will pass for other pulls.

**Comment by jpince** [comment]
@stian-sigvartsen reverted here, please recommit when you're ready https://github.com/liferay/liferay-portal/compare/eba358f...87b9218

**Comment by stian-sigvartsen** [comment]
Was resent to Brian

**Pull request closed without merging**
