### PR TITLE
LPS-90322 | Remove jQuery from the oauth2-provider-web module

### PR DESCRIPTION
**Pull request by topolik**
Hi Stian,

can you please review the OAuth2 javascripts? You have much better understanding of how it works.

Thank you.

/cc @kresimir-coko @markocikos

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Will do. Thanks @kresimir-coko @markocikos

**Comment by markocikos** [comment]
@stian-sigvartsen Please review PR, it's been open 16 days.

/cc @topolik

**Comment by martamedio** [comment]
Hey @markocikos and @kresimir-coko, sorry for the delay
@stian-sigvartsen is on PTO, I've reviewed it and sent it: https://github.com/brianchandotcom/liferay-portal/pull/69927

**Comment by markocikos** [comment]
@martamedio Thank you!

**Pull request closed without merging**
