### PR TITLE
LPS-175232 tests

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Hi @nikolettabuza . In [32c8e93](https://github.com/stian-sigvartsen/liferay-portal/pull/285/commits/32c8e930ee1a6c95dfc142b37d1c1e1a8438f0af) you are changing the "else if" after the earlier "if" statements that check using "startsWith". My expectation is that a full match would be attempted before any "startsWith". This way if customers have registered an `Encryptor` which is currently matching on the full algorithm string, then that will continue after our change also.

**Comment by nikolettabuza** [comment]
Hi @stian-sigvartsen,
that is what the commit is about, a full match is attempted first, just before trying to find a match without the arguments in the commit you mention:
```
if (algorithm.startsWith(TYPE_BCRYPT)) {
}
else if (algorithm.startsWith(TYPE_PBKDF2)) {
}
else if (algorithm.indexOf(CharPool.SLASH) > 0) {
	passwordEncryptor = _serviceTrackerMap.getService(algorithm);

	if (passwordEncryptor == null) {
		passwordEncryptor = _serviceTrackerMap.getService(
			algorithm.substring(0, algorithm.indexOf(CharPool.SLASH)));
	}
}
else {
    	passwordEncryptor = _serviceTrackerMap.getService(algorithm);	
}
```
Can you please look at the `else if` block again that dnebinger created? I added `passwordEncryptor = _serviceTrackerMap.getService(algorithm);` to it, then I check if the PwEncryptor is assigned with a full match or not, if not, only THEN we can use the new approach.
That `else if` block handles the encryptors that are not PBKDF2/BCRYPT but have arguments. First we use the original approach (the algorithm has to be an exact match), if that fails, then we use the new approach (try to match without the arguments).
If they are not PBKDF2/BCRYPT and do not have arguments, they end up in the `else` block, same as before.

**Comment by nikolettabuza** [comment]
@stian-sigvartsen 
Another approach could be removing the new `else if` block and add it's part to the already existing `else` block. In case the passwordEncryptor is still `null` after trying for an exact match, we can try to match without the arguments:
```
else if (algorithm.startsWith(TYPE_PBKDF2)) {
}
else {
	passwordEncryptor = _serviceTrackerMap.getService(algorithm);

	if ((passwordEncryptor == null) && (algorithm.indexOf(CharPool.SLASH) > 0)) {
		passwordEncryptor = _serviceTrackerMap.getService(
			algorithm.substring(0, algorithm.indexOf(CharPool.SLASH)));
	}
}
```

**Comment by stian-sigvartsen** [comment]
Looking good!

**Pull request closed without merging**
