### PR TITLE
LPS-72931 semantic versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
@marianoalvarosaiz @JavierMoral Did you explore adding the priority as an index to the exiting LDAPServerConfiguration instead of creating a new one?

**Comment by JavierMoral** [comment]
Hi Stian,
that was our initial idea but our main concern about it was the possibility
of users changing that value through system settings. Considering that, we
created the new configuration in a way that it is not shown in system
settings.
We also considered including it as a field in LDAPAuthConfiguration but the
idea was discarded for the same reason.

On Fri, Jun 16, 2017 at 11:36 AM, Stian Sigvartsen <notifications@github.com

**Comment by stian-sigvartsen** [comment]
Would it matter if users change it via System Settings? I mean the index would be relative to other LDAPServerConfiguration instances so ordering is maintained. Unless of course two have the same index in which case ordering is undefined and this could be stated in System Settings

**Comment by JavierMoral** [comment]
Our concern was not limited exclusively to users changing the values. We
consider this an internal, calculated configuration and think that
appearing in system settings would constitute a poor user experience. Users
would have to manually input the index without seeing the other values as a
reference. This would cause confusion, conflicts and errors. That's why it
is not implemented like that in instance settings and users can sort the
servers using the arrows instead.

On Fri, Jun 16, 2017 at 12:31 PM, Stian Sigvartsen <notifications@github.com

**Comment by stian-sigvartsen** [comment]
I had the same concern, only the other way around. Because you would need to know the ldapServerIds to update the configuration manually. But this is only a concern if the configuration is visible via System Settings. Is it not visible for you via a search for "LDAP"?

**Comment by topolik** [comment]
Hi guys,

for me the root cause is that we do not allow developers to specify how configuration fields are processed by system settings.

Imagine we could say the `priority` is invisible or read-only. Or add a validation script there. 

We cannot, so we move that field outside LDAPSystemConfiguration while we all agree it's wrong and it belongs there. 

Creating a new configuration object with mandatory relation 1:1 is more error prone than leaving one field for user to edit, knowing user can find and edit it anyway.

For me the bug is that we can't influence how configuration fields are presented to user and validated in system settings.

**Comment by marianoalvarosaiz** [comment]
Hi @stian-sigvartsen, @stian-sigvartsen,
 considering that none of both solutions seem optimal we would implement yours, adding a new element in the LDAPServerConfiguration. This will mean modifying the edition JSP to explicitly not show that field in instance settings configuration and put a help message in the system settings configuration to tell the user that the value inserted will be discarded.

Taking into account that it is a poor usability issue and that it could be a perceived bug by the user, do you have in mind how could we proceed in that situation?

Thanks.

PS: Do you know if there is any initiative to allow read-only or invisible fields in configuration? Also, are we going to implement any additional restriction so that not every configuration is shown in system settings when searching.

**Comment by stian-sigvartsen** [comment]
Hey @marianoalvarosaiz . We've found a tweak to the approach which means the priority property will not be rendered by System Settings. So all UIs will stay the same as now and there will be no new UX issue. This is made possible by simply excluding the priority property from the LDAPServerConfiguration metatype. We can still set the property when updating the configuration via the Config Admin API (i.e. no change in approach) and it will be persisted.

Additionally since it is not possible to configure LDAPServerConfiguration at the company scope via System Settings (only defaults for all companies can be set), admins would only ever need to specify the priority value manually if they are configuring via files.

I intend to work on implementing this solution later this afternoon so we should have a fix for the customer soon.

**Comment by JavierMoral** [comment]
Hi @stian-sigvartsen. Did you have time to look into this issue? May we help you in any way?

**Comment by topolik** [comment]
Hi @JavierMoral, 

@stian-sigvartsen started the work on it yesterday. But he's on holidays from today till end of the week so he probably didn't manage to finish it.

He discussed the work with @csierra, so maybe Carlos knows how that finished. 

If not, me or @csierra can do it instead.

**Comment by stian-sigvartsen** [comment]
Hi @JavierMoral . Apologies I wasn't able to complete this work before my holidays (back Monday). I am sending the changes so far to @csierra so hopefully he can complete it. Otherwise I will pick it up again on Monday.

**Pull request closed without merging**
