### PR TITLE
[LRSUPPORT] LPS-99556 set threadlocal to ensure that password gets exported to LDAP

### PR DESCRIPTION
**Pull request by JavierMoral**
Hi,
I'm sending this pull to fix [https://issues.liferay.com/browse/LPS-99556](https://issues.liferay.com/browse/LPS-99556).
It has to do with password export to LDAP.
Could you take a look a it please?

Thanks!

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Just started reviewing...

**Comment by stian-sigvartsen** [comment]
Looks good! Forwarded to brianchandotcom/liferay-portal/pull/76926

**Pull request closed without merging**
