### PR TITLE
OAUTH2-292 Add default value to removed-scope checkbox

### PR DESCRIPTION
**Pull request by martamedio**
As we have discussed, there seems to be a premeditated behavior behind the AUI-checkbox to transform its content when it has no value.

I have added a default value to avoid problems.

### CODE REVIEW

**Comment by martamedio** [comment]
Looks like this PR we will solve also: https://issues.liferay.com/browse/OAUTH2-288

**Comment by martamedio** [comment]
ci:test:sf

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
The approach looks good, I just tweaked what we are sending. Please see https://github.com/martamedio/liferay-portal/pull/103

**Pull request closed without merging**
