### PR TITLE
LPS-102185

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79585

**Comment by ChrisKian** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/909

**Comment by stian-sigvartsen** [comment]
Waiting on the outcome from drewbrokke/liferay-portal/pull/909

**Comment by stian-sigvartsen** [comment]
See brianchandotcom/liferay-portal/pull/80873

**Pull request closed without merging**
