### PR TITLE
[TS] LPS-106904 NullPointerException during login with OpenID Connect (SwissID)

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-106904

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:security

**Comment by joshchong** [comment]
ci:test:security

**Comment by joshchong** [comment]
@NorbertKocsis @lipusz The text fix for `Login#OpenIDConnectSmoke` was pushed upstream and the test passed in this PR:
https://testray.liferay.com/home/-/testray/case_results/952291749

I also confirmed all the other failures from the `ci:test:security` run are occurring upstream and are unrelated.

**Comment by lipusz** [comment]
Thanks a lot, @joshchong!

**Comment by stian-sigvartsen** [comment]
Looks great @NorbertKocsis . Please see brianchandotcom/liferay-portal/pull/83264

**Pull request closed without merging**
