### PR TITLE
OAUTH2-109 OAuth2 Provider Scopes API for JAX-RS applications to use annotation to declare and check scopes

### PR DESCRIPTION
**Pull request by topolik**
Hi,
I added a paragraph in javadoc about the scopes inheritancy.

@stian-sigvartsen, can you please look at it and send to Brian?

Thanks!

https://issues.liferay.com/browse/OAUTH2-109

/cc @csierra

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by stian-sigvartsen** [comment]
Reads well. I think we should explain elsewhere how a request becomes "authorized".
Just waiting for a successful CI test.

**Comment by topolik** [comment]
ci:reopen

CI failure

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by topolik** [comment]
@stian-sigvartsen, do you plan to change anything? If not, can you please send it to Brian? 

Thanks.

**Comment by stian-sigvartsen** [comment]
Was just waiting for a successful CI test, but as we've just discussed the issues are definitely unrelated to our changes.

Forward to brianchandotcom/liferay-portal/pull/55593

**Pull request closed without merging**
