### PR TITLE
[TS] LPS-69762 Unable to include .tpl file in a layout template (regression)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-69762

Hi Stian,

I'm forwarding this to you as Tomas is OoO this week. Please see further details on the ticket. You'll know the background. ;-)

Thanks,
Tibor

----
Author: @ugurcancetin
Reviewers: @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Rebased to latest master.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Stian,

Can you please review this pull and push forward?

Thanks,
Tibi

@stian-sigvartsen

**Comment by stian-sigvartsen** [comment]
Hi Tibor. Just starting to look at it now.

@lipusz

**Comment by lipusz** [comment]
Thanks, Stian!

**Comment by stian-sigvartsen** [comment]
Looks good, forward to brianchandotcom/liferay-portal/pull/46192

**Pull request closed without merging**
