### PR TITLE
LPS-99587

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPP-34757
https://issues.liferay.com/browse/LPS-99587

Notes from @jesseyeh-liferay:

> ## Problem
> 
> This is a continuation of this [pull request](https://github.com/brianchandotcom/liferay-portal/pull/79098) for [LPS-99587](https://issues.liferay.com/browse/LPS-99587) that adds the required tests.
> 
> ## Solution
> 
> Tests have been added to verify that the prerequisites, `setEmailAddress` and `setScreenName`, have been called prior to calling `setDigest`. The tests check against all calling order permutations (i.e., the order in which `setEmailAddress` and `setScreenName` are called relative to `setDigest`) for `IllegalStateException` when the test should fail.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by lipusz** [comment]
Hey @ChrisKian 

Please add the "[TS]" designation to the subject to indicate it's coming from TS. Thanks!

**Comment by stian-sigvartsen** [comment]
Hey @ChrisKian . The test that was created tests expected behavior the getDigest() method itself, not the usage of it. I believe what BChan is after is a test which fails if the order of the prerequisite method invocations are not called beforehand when creating a new user.

When this happens, so many tests start failing (and Jenkins jobs start timing out etc.) that it becomes very difficult to pinpoint the underlying problem.

Does that make sense?

**Comment by ChrisKian** [comment]
Hey @stian-sigvartsen,

Thanks for the detailed info, we will look into it and resend a PR when ready.

CC @wanderlast and @jesseyeh-liferay

**Pull request closed without merging**
