### PR TITLE
[TS] LPS-102185 Token Based SSO is not working at instance level

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-102185

Modifications are based on our documentation:
https://portal.liferay.dev/docs/7-2/frameworks/-/knowledge_base/f/scoping-configurations

Thanks!
Norbert

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Just started reviewing...

**Comment by NorbertKocsis** [comment]
Hi,

Did you have a chance to tak a look at this, or is there anything I should do?

Br,
Norbert

**Comment by stian-sigvartsen** [comment]
Hi Nobert. Sorry I should have kept you informed better. I reviewed this last week and concluded we should have consistency between all the SSOs. Token SSO has got TokenConstants.SERVICE_NAME which should be used for company scope of the configuration (gets stored into PortletPreferences). With the changes you proposed the configuration is stored using the new scopeable configuration style PIDs. Which normally would be fine, but I feel consistency wins out in this case. Unfortunately to achieve this there was a lot more work required like custom JSPs. It's soon ready for review.

**Comment by NorbertKocsis** [comment]
Hi,

Thanks for the quick reponse! I'll wait for the final changes then.

Br,
Norbert

**Comment by stian-sigvartsen** [comment]
Sent the final changes here: csierra/liferay-portal/pull/557

**Pull request closed without merging**
