### PR TITLE
[TS] LPS-113260

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @stian-sigvartsen ,

I was wondering if you could help review this PR, if you're not the right person to review this, please let me know if you know who I should forward this to.

**Context**
This PR fixes an issue where: the Forget Password email includes URLs that do not provide the proper protocol (http vs https) when using X-Forwarded-* headers.

This issue does not exist in 71x and was introduced in 72x by [LPS-100825](https://issues.liferay.com/browse/LPS-100825). 

From what I can tell, generating the portalURL by using the portletRequest, may not return a URL with the same HTTP/HTTPS protocol that the main httpServletRequest is expected to provide.

**Proposed Fix**
For this PR, I decided to replace the portalURL in the serviceContext that was set by the ServiceContextFactory.

Instead, we set the portalURL with the value that's stored in the themeDisplay, which includes the proper protocol, hostname, port, proxy, etc.

I figured this was reasonable, since looking at the service call, the serviceContext.getPortalURL() is used for crafting links for the forget password email content.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @ericyanLr . I'm reviewing :)

**Comment by stian-sigvartsen** [comment]
Hi @ericyanLr . Thanks for describing your analysis and rationale. 

> From what I can tell, generating the portalURL by using the portletRequest, may not return a URL with the same HTTP/HTTPS protocol that the main httpServletRequest is expected to provide.

I think you discovered a long standing generic issue here. Rather than patch it just for Forgot Password (```LoginUtil```), I think we should fix it more generally.

I have sent a proposal to Tomas who has more experience with ```PortalImpl```. Please see topolik/liferay-portal/pull/835

**Comment by ericyanLr** [comment]
Hi @stian-sigvartsen ,

Thanks for the update and looking into this! 
I'll be following the PR chain.

**Pull request closed without merging**
