### PR TITLE
LPS-100949

### PR DESCRIPTION
**Pull request by brianikim**
Resending from: https://github.com/stian-sigvartsen/liferay-portal/pull/185

Notes from Me:
> 
> > https://issues.liferay.com/browse/LPS-100949

> > This is a security fix. Please see ticket for further details.

> > As for the fix, we are applying a patched version of cas-client-core version 3.1.12 to include the commit from here: [apereo/java-cas-client@ae37092](https://github.com/apereo/java-cas-client/commit/ae37092100c8eaec610dab6d83e5e05a8ee58814) which addresses the vulnerability found and mentioned in the ticket.

> > Please let me know if you have any questions. Thanks.

> > Sincerely,
> > Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
Hello @stian-sigvartsen ,

We need an update on this PR. Thanks.

Sincerely,
Brian Kim

**Comment by stian-sigvartsen** [comment]
hi @brianikim . I will be reviewing this pull request first thing in the morning (GMT).

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
@brianikim It isn't clear on the pull or ticket if you explored upgrading the library instead of patching it?

Looks like we are on the latest 3.1.x so we'd need to jump a minor version so there might be some incompatibility?

**Comment by brianikim** [comment]
Hey @stian-sigvartsen ,

In order for us to upgrade the library, we would have to upgrade cas-client-core to at least 3.3.2 which involves a major dependency version jump for opensaml. I opted for the patch version because it was much more time & effort-efficient.

Sincerely,
Brian Kim

**Comment by stian-sigvartsen** [comment]
Thanks @brianikim . We're a bit cautious with applying this patch because there are limited automated tests for the CAS modules, so we will need to discuss it in our team tomorrow.
Can you let me know what kind of testing you have already done?

**Comment by brianikim** [comment]
I did not include in this patch as I saw, in past patched jars, we did not include test classes. But CASC-228 (https://github.com/apereo/java-cas-client/commit/ae37092100c8eaec610dab6d83e5e05a8ee58814) contains the test method that is designed to test the new implementation which I used to confirm that the asserts passed.

Sincerely,
Brian Kim

**Comment by stian-sigvartsen** [comment]
That's good on terms of verifying cherrypicking this commit will not break the CAS library. Did you do any smoke/functional testing of the use of the patched JAR in portal?

**Comment by brianikim** [comment]
Hello @stian-sigvartsen ,

I did not. The most I did was running the integration tests that we have in-place.

Sincerely,
Brian Kim

**Comment by stian-sigvartsen** [comment]
Hey @brianikim . We discussed the patch this morning and it was concluded that we would like to explore upgrading CAS client and also OpenSAML. In the long term this is a easier to maintain approach, and it is especially important given that CAS support is deprecated in 7.2. i.e. we don't want to maintain a patched version.

I'm working on testing an upgrade with a CAS server.

**Comment by brianikim** [comment]
Hello @stian-sigvartsen,

any updates on your testing? Also, please let me know if this PR should be closed. Thanks.

Sincerely,
Brian Kim

**Comment by stian-sigvartsen** [comment]
Hey @brianikim . We've had delays in configuring a CAS server for manual testing. Let's leave the PR open until we have tested this.

**Comment by stian-sigvartsen** [comment]
Hi @brianikim . Let's close this pull request because we are working on a different implementation (dependency versions change). If we need to revert to this original pull request (after smoke testing) then I will create a new pull request.

**Comment by stian-sigvartsen** [comment]
Please see brianchandotcom/liferay-portal/pull/79691

**Pull request closed without merging**
