### PR TITLE
[TS] LPS-114541

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@stian-sigvartsen Did you have a chance to review these changes? If you'd rather someone else take a look at it I can forward it along to them as well. Thank you.

**Comment by stian-sigvartsen** [comment]
Hey @jonathanmccann . I'm in the process of reviewing it. Did you explore other approaches that do not rely on ThreadLocals? I'm keen that we avoid adding technical debt if at all possible.

I can see that the underlying cause of the bug is that the UserModelListener is invoked multiple times.

**Comment by jonathanmccann** [comment]
I used the fix for LPS-76332 as a basis since that pattern was already in use. I did not pursue a different approach because I believe that changing how many times the user is updated would have been a large overhaul and most likely not backportable for the client. I outlined where the updates to the user are occurring here - https://issues.liferay.com/browse/LPP-37600?focusedCommentId=2165561&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2165561

If you have any ideas I'm willing to try them out.

**Comment by stian-sigvartsen** [comment]
I didn't see your comments on that ticket. They would have been useful :|
Your reasoning is sensible. I'll try to wrap this review up tomorrow.

**Comment by jonathanmccann** [comment]
Thank you for looking over it. If you need me to test anything let me know.

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
@jonathanmccann Looks like a sensible fix, especially as it is based on existing code.

I will later consider if we can do some refactoring to avoid exporting 3 times to LDAP as this appears to have been a behavior that was introduced after 7.0.x. But I'll raise a separate ticket.

**Pull request closed without merging**
