### PR TITLE
LPS-85171 add warning for account creation URL with openID

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @stian-sigvartsen ,
I saw you had activity on this ticket, so I want to send PR to you.

ps: can you just remove the openId parameter from the page? Or is it used for something else, like when redirecting back from openId server? Also isnt openId about to obsolute?

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
Thanks @arthurchan35 , looks good!
Please see https://github.com/brianchandotcom/liferay-portal/pull/71200

**Pull request closed without merging**
