### PR TITLE
LPS-170940

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@stian-sigvartsen see https://github.com/brianchandotcom/liferay-portal/pull/130256

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:security

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@JessieZhao0714 @gaborlovasdotcom fyi. I'm not sure if reviewing the test results is part of your normal team workflow, but I wanted to make you aware of this PR.

**Comment by jpince** [comment]
SF failures are consistent with ones in [upstream|https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp-downstream(master)/24390/console]. I'm not sure why the other test jobs failed.

**Comment by stian-sigvartsen** [comment]
See brianchandotcom/liferay-portal/pull/130806

**Pull request closed without merging**
