### PR TITLE
[TS] LPS-116250

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hi @stian-sigvartsen,

The issue at hand is that the user is logged out because their password modified date becomes newer than their session create date (This logout happens in the `PasswordModifiedFilter`).

The issue is caused by the changes made in [LPS-85179](https://issues.liferay.com/browse/LPS-85179). The reason why I'm partially reverting LPS-85179 is because that issue is still reproducible. I have opened [LPS-116251](https://issues.liferay.com/browse/LPS-116251) to track it.

Since that issue still exists I thought it would be best to remove the code that is causing the current issue because it is not fixing anything.

Please let me know if you have any questions or concerns. If there is a better resolution I'd be more than happy to test it as well.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Hey @jonathanmccann . Just to let you know I'm close to finishing my review. I'll be in touch soon.

**Comment by stian-sigvartsen** [comment]
Thanks @jonathanmccann ! We would have a regression in handling when passwords are changed on the LDAP server. I've extended your solution to fix. Please see jonathanmccann/liferay-portal/pull/1844

**Pull request closed without merging**
