### PR TITLE
LPS-63213

### PR DESCRIPTION
**Pull request by jcampoy**
rebased master. details: https://github.com/stian-sigvartsen/liferay-portal/pull/58#issue-208252363  issue: https://issues.liferay.com/browse/LPS-63213

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:reopen

**Comment by jcampoy** [comment]
Hi @stian-sigvartsen , I think this test is not broken by my changes because it is not related with them.

**Comment by stian-sigvartsen** [comment]
Started reviewing...

**Comment by stian-sigvartsen** [comment]
Hi @jcampoy. These changes look good until the taglib is reviewed. Thanks!
Pushed to brianchandotcom/liferay-portal/pull/47073

**Pull request closed without merging**
