### PR TITLE
LPS-115796

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks @martamedio for offering to review this

**Comment by martamedio** [comment]
Tested using [Wordpress](https://grow.liferay.com/share/How+to+login+using+OpenID+authentication_QUESTION_)

ci:forward

**Comment by martamedio** [comment]
ci:forward

**Pull request closed without merging**
