### PR TITLE
Crypto osgi

### PR DESCRIPTION
**Pull request by arthurchan35**
Here is the OSGi integration part for the Crypto Hash.
We have introduced the Apache Aries Component DSL because it allows us to provide the features we need without having to significantly alter the existing classes (just add a couple of annotations to the existing factories to make them components)

Features are:

- CryptoHashProviderFactories are tracked and registered in the registry.
- If the factories have an associated configuration.pid the integration will track configurations for those pids.
- If a configuration for that pid exists it will register a CryptoHashGenerator using that configuration.
- Registered CryptoHashGenerator services will bear the properties on the service together with the factory name to allow filtering by hashing properties.
- The CryptoHashVerifier will work without any existing configuration as long as the corresponding provider is registered. This allows to verify existing hashes that have been generated with weaker configurations and generate new hashes with stronger ones.
- The factories are tracked by name, making it possible to replace an existing factory with a different implementation with a higher ranking. Regardless of the configuration pid the same factory needs to be used for generation and verification.
- Configurations are created scoped by company, so services that are going to make use of this framework may make use of a scoped service tracker.

### CODE REVIEW

**Comment by arthurchan35** [comment]
@stian-sigvartsen 
@martamedio

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
@stian-sigvartsen @martamedio 

I think I forgot to SF the build.gradle

That's the only problem left with this pull.

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
@stian-sigvartsen @martamedio 
NVM my previous message, I have SFed the pull.
It's rerunning.

**Comment by stian-sigvartsen** [comment]
@arthurchan35 this looks good! I'm forwarding, sorry for the delay.

/cc @martamedio

**Comment by stian-sigvartsen** [comment]
ci:forward

**Pull request closed without merging**
