### PR TITLE
[TECHNICAL-SUPPORT] LPS-69601

### PR DESCRIPTION
**Pull request by topolik**
Stian, can you please review? Thank you!

----

For more information, please see https://issues.liferay.com/browse/LPS-69601?focusedCommentId=910323&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-910323

/cc @dustinryerson

### CODE REVIEW

**Comment by topolik** [comment]
ci:reopen

**Comment by dustinryerson** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
See dustinryerson/liferay-portal/pull/95

**Comment by topolik** [comment]
Thanks a lot, Stian!

**Pull request closed without merging**
