### PR TITLE
COMMERCE-6815 Commerce Price List - fix usage of hasOwnerPermission

### PR DESCRIPTION
**Pull request by igorbeslic**
Stian, you did review COMMERCE-6816. This one is same, but different module. Should not be too complex. Thank you very much.

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:forward

**Comment by stian-sigvartsen** [comment]
Looks good @igorbeslic !

**Pull request closed without merging**
