### PR TITLE
[TECHNICAL-SUPPORT] LPS-105803

### PR DESCRIPTION
**Pull request by jonathanmccann**
@stian-sigvartsen,

If the SSOImpl returns the CAS login URL then the CASFilter is completely bypassed and we lose all of the benefits of running through it. This change makes it similar to NTLM's SSOImpl by returning the default login URL so that we are routed through the CASFilter.

Please let me know if you have any questions or see any potential issues.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by csierra** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by xbrianlee** [comment]
ci:test:bundle:norebase

**Comment by xbrianlee** [comment]
ci:test:bundle:norebase

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/82188

ci:close

**Pull request closed without merging**
