### PR TITLE
LPS-109015 Do not execute during startup (as soon as an interval trigger gets scheduled it's fired). To import users on startup we already have LDAPPortalInstanceLifecycleListener, that can be configured via OSGi.

### PR DESCRIPTION
**Pull request by csierra**
/cc @martamedio

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant:norebase

**Comment by lipusz** [comment]
ci:test:security:norebase

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
Thanks for picking this up @martamedio ! Linking brianchandotcom/liferay-portal/pull/85424

**Pull request closed without merging**
